name: Test PR Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  playground-preview:
    name: Test Preview Comment
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ./.github/workflows/playground-preview.yml
    with:
      preview-mode: "comment"
